# Site settings
title: Center for Applied Network Analysis (CANA)
email: tvalente@usc.edu
description: > # this means to ignore newlines until "baseurl:"
 Oficial website of USC's Center for Applied Network Analysis 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://USCCANA.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  USCCANA

# Build settings
markdown: kramdown
exclude: [about.md]